"""create_skills

Revision ID: 2942cdaaec4e
Revises: 93317f5809f3
Create Date: 2026-01-11 09:12:37.232658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2942cdaaec4e'
down_revision: Union[str, Sequence[str], None] = '93317f5809f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user_skills', sa.Column('skill_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_skills', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key(None, 'user_skills', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.drop_column('user_skills', 'skill_id')
    op.drop_column('user_skills', 'user_id')
    # ### end Alembic commands ###
