"""add_ondelete_cascade_in_user_skills

Revision ID: 4e708028f7f7
Revises: 2942cdaaec4e
Create Date: 2026-01-11 17:43:22.581817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e708028f7f7'
down_revision: Union[str, Sequence[str], None] = '2942cdaaec4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_skills_user_id_fkey'), 'user_skills', type_='foreignkey')
    op.create_foreign_key(None, 'user_skills', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.create_foreign_key(op.f('user_skills_user_id_fkey'), 'user_skills', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
