"""add_init_false_in_relationship_column

Revision ID: 93317f5809f3
Revises: d16a1a62ea2a
Create Date: 2026-01-11 05:51:06.278348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93317f5809f3'
down_revision: Union[str, Sequence[str], None] = 'd16a1a62ea2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
