"""Добавил RefreshSessionModel v2 добавил init false

Revision ID: c4ca0dd86a78
Revises: f63074718895
Create Date: 2026-01-17 06:08:56.194024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ca0dd86a78'
down_revision: Union[str, Sequence[str], None] = 'f63074718895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
