"""add_post v1

Revision ID: df28eaa708d9
Revises: 4e708028f7f7
Create Date: 2026-01-13 17:36:30.169775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df28eaa708d9'
down_revision: Union[str, Sequence[str], None] = '4e708028f7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('user_fk', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'user_fk')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
