"""Добавил RefreshSessionModel

Revision ID: f63074718895
Revises: a87bd4243c28
Create Date: 2026-01-17 05:33:02.026039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63074718895'
down_revision: Union[str, Sequence[str], None] = 'a87bd4243c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.String(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=True)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'user_id')
    op.drop_column('refresh_tokens', 'refresh_token')
    # ### end Alembic commands ###
